name: ci

on:
  push:

concurrency:
  group: build-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Build artifacts
        run: ./gradlew build --no-daemon --stacktrace

      - name: Get project version
        if: ${{ github.ref_name == 'master' }}
        id: get_version
        shell: bash
        run: |
          project_version=$(./gradlew -q --console=plain printVersion --no-daemon)
          echo version=$project_version >> $GITHUB_OUTPUT

      - name: Copy artifacts before uploading
        if: ${{ github.ref_name == 'master' }}
        run: cp build/libs/TreasureMapsPlus-${{ steps.get_version.outputs.version }}-all.jar TreasureMapsPlus.jar

      - name: Generate SHA-256 hash
        if: ${{ github.ref_name == 'master' }}
        run: sha256sum TreasureMapsPlus.jar > TreasureMapsPlus.jar.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ github.ref_name == 'master' }}
        with:
          name: TreasureMapsPlus
          path: |
            TreasureMapsPlus.jar
            TreasureMapsPlus.jar.sha256
            LICENSE
            README.md

      - name: Generate Build Summary
        uses: actions/github-script@v7
        if: ${{ github.ref_name == 'master' }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;

            core.summary
              .addHeading('Download', 3)
              .addLink('TreasureMapsPlus.zip', `https://nightly.link/${owner}/${repo}/actions/runs/${run_id}/TreasureMapsPlus.zip`)
              .write();
