name: Semantic PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  merge_group:
    types:
      - checks_requested

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        if: ${{ github.event_name != 'merge_group' }}
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
